<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>promise的几个关键问题</title>
</head>
<body>
<script>
    /* 
    6.promise异常传透?
      (1)当使用promise的then链式调用时, 可以在最后指定失败的回调, 
      (2)前面任何操作出了异常, 都会传到最后失败的回调中处理
    7.中断promise链?
      (1)当使用promise的then链式调用时, 在中间中断, 不再调用后面的回调函数
      (2)办法: 在回调函数中返回一个pendding状态的promise对象
    */
    new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('执行任务1（异步）')
            // resolve(1)
            reject(1)
        }, 1000)
    }).then(//status == 'resolved' value ==  1
        value => {
            console.log('onResolved1()：', value) //1
            return 2
        },
        reason => {throw reason} //这一行没写，相当于写了这一行
    ).then( // status == 'resolved' value ==  2
        value => {
            console.log('onResolved2()：', value) //2
            return 3
        },
        reason => {throw reason} //这一行没写，相当于写了这一行
    ).then(
        value => {
            console.log('onResolved3()：', value)
        },
        reason => {throw reason} //这一行没写，相当于写了这一行
    ).catch(reason => {
        console.log('onRejected1()', reason)
        // throw reason
        return new Promise(()=>{}) //返回一个pending的promise 中断promise链
    }).then(
        value => {
            console.log('onResolved4()：', value)
        },
        reason => {
            console.log('onRejected()', reason)
        }
    )
    console.log('--------------')

</script>
</body>
</html>